image: feeni/node-chrome:latest

clone:
  depth: full              # SonarCloud scanner needs the full history to assign issues properly

definitions:
  caches:
    sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build
  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarCloud
        caches:
          - node
          - sonar
        script:
          - npm install --quiet
          - npm run test -- --code-coverage --no-watch --no-progress --browsers=ChromeHeadlessNoSandbox  
          - pipe: sonarsource/sonarcloud-scan:use-pipe-storage-and-default-vars
            variables:
              EXTRA_ARGS: '-Dsonar.sources=src -Dsonar.tests=src -Dsonar.test.inclusions="**/testing/**,**/*.spec.ts" -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info'
    - step: &quality-gate-check
        name: Check Quality Gate on SonarCloud
        script:
          - pipe: sonarsource/sonarcloud-quality-gate:feature-implement-quality-gate-check
    - step: &release
        name: Release
        script:
          - echo "Good to deploy!"
pipelines:
  default:
    - step: *build-test-sonarcloud
    - step: *quality-gate-check
    - step: *release
  pull-requests:
    '**':
      - step: *build-test-sonarcloud
      - step: *quality-gate-check
      - step: *release
