image: circleci/node:8-browsers

clone:
  depth: full              # SonarCloud scanner needs the full history to assign issues properly

definitions:
  caches:
    sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build
  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarCloud
        caches:
          - node
          - sonar
        script:
          - npm install
          - npm run test -- --no-watch --no-progress --browsers=ChromeHeadless         
          - pipe: SonarSource/sonarcloud-scan:0.1.1
            environment:
              SONAR_TOKEN: ${SONAR_TOKEN}
              EXTRA_ARGS: '-Dsonar.sources=. -Dsonar.exclusions="node_modules/**" -Dsonar.projectKey=sonarsource_sample-nodejs-project -Dsonar.organization=sonarsource-bitbucket'
pipelines:
  default:
    - step: *build-test-sonarcloud
  pull-requests:
    '**':
      - step: *build-test-sonarcloud
